name: Go Tests
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        golang:
          - '1.24'
          - '1.25'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ${{ matrix.golang }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.golang }}
        id: go
      - name: Check out code
        uses: actions/checkout@v5
      - name: Test
        run: go test -v ./...
