name: Go Tests
on: [push, pull_request]
jobs:
  test-1_19:
    name: Test 1.19
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: go test -v ./...

  test-1_20:
    name: Test 1.20
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: Test
        run: go test -v ./...
